services:
    challenge:
      # <category-name>-<challenge-name>
      container_name: pwn-ord
      build: service
      # Required if you're using pwn.Dockerfile
      privileged: true
      ports:
        # host port: container port
        # Will be used in generation of CTFd connection info
        - 32832:5000